export const photoExamples = [
  "/example-h.png",
  "/example.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
  "/example-h.png",
  "/example-h.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
];

export const videoExamples = [
  "/example.png",
  "/example-h.png",
  "/example-h.png",
  "/example.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
  "/example.png",
  "/example-h.png",
  "/example.png",
  "/example-h.png",
  "/example-h.png",
  "/example.png",
  "/example.png",
  "/example-h.png",
  "/example-h.png",
];
